### ISSUE TITLE
Difference between Table 11 of the paper and results for xgqa

### ISSUE THREAD

**Issue by nooralahzadeh** [e-bug/iglue#1]
Hi
I wonder what is the difference between the numbers in `https://github.com/e-bug/iglue/tree/main/results/xgqa/xGQA_0.csv`and Table 11 of the paper (for example on UC2).
It seems also you excluded `en` from `avg`.
Thanks

**Comment by e-bug** [comment]
Exactly. As mentioned in the paper, English is only used for training and it is not considered for cross-lingual evaluation.

**Comment by nooralahzadeh** [comment]
How about the first question? :)

**Comment by e-bug** [comment]
The results in Table 11 are for the ['zero-shot' split of xGQA](https://github.com/e-bug/iglue/tree/main/datasets/xGQA/annotations/zero_shot).
We computed those results solely to compare against [Pfeiffer et al. (2021)](https://arxiv.org/abs/2109.06082).

IGLUE always relies on the test set of the ['few-shot' split of xGQA](https://github.com/e-bug/iglue/tree/main/datasets/xGQA/annotations/few_shot) for 1:1 comparisons between zero-shot and few-shot experiments.

**Comment by nooralahzadeh** [comment]
Great, thanks for the clarification. Table 14 is align with the results in `https://github.com/e-bug/iglue/tree/main/results/xgqa/xGQA_0.csv`
