### ISSUE TITLE
MaRVL does not have english test set, which set did you use in Table 3? 

### ISSUE THREAD

**Issue by zengyan-97** [e-bug/iglue#10]
Hi, 

Table 3 reports model performance "on English splits of the IGLUE tasks". 
So, I assume that you used corresponding en test set of iglue. 
But, MaRVL does not have an english test set... So, which dataset did you use in Table 3? 

Thanks!

**Comment by e-bug** [comment]
Hi, sorry for the confusion! The corresponding English test set for MaRVL is the `Test-P` split from NLVR2.

**Comment by zengyan-97** [comment]
Thanks!
