### ISSUE TITLE
Cannot find raw image in MaRVL few-shot train set

### ISSUE THREAD

**Issue by memory4963** [e-bug/iglue#11]
Hi, sorry for bothering again.

I found there is no raw image (.jpg) for some of the images in the MaRVL few-shot train set, could you tell me where to find or download them?
For example, I can find `52-火锅/52-5.jpg`, but cannot find `52-火锅/52-n-5.jpg` in 'zh'.

I know there are feature files for few-shot images, but we are extracting the visual features with our own network.

**Comment by e-bug** [comment]
Hi, sorry for the inconvenience. We are about to upload the MaRVL few-shot data to the Dataverse repository. 
I will send a new reply here once the data has been uploaded.

**Comment by memory4963** [comment]
Thank you! And I will appreciate it if you upload it this week because we are going to submit a paper soon :)

**Comment by e-bug** [comment]
Hi, my collaborator that has access to Dataverse is OOO.
If you email me, I'll share the data with you (the same [CC BY 4.0 license](https://creativecommons.org/licenses/by/4.0/deed.ast) applies).
