### ISSUE TITLE
Calculation of translate-test scores

### ISSUE THREAD

**Issue by memory4963** [e-bug/iglue#12]
Hi, another question I want to ask.

For the translate-test experiments, did you combine all the translated test sets and then calculate the score, or, calculate scores separated by language, then average them?

**Comment by e-bug** [comment]
Hi, we simply calculate scores separated by language and then average them.

You can see this implemented [here](https://github.com/e-bug/iglue/blob/main/notebooks/Results-AVG.ipynb) and described in page 7 of the paper (second line of `Transfer Gap` paragraph).

**Comment by memory4963** [comment]
I will check it out, thank you very much!
