### ISSUE TITLE
Zero-shot evaluation crashes

### ISSUE THREAD

**Issue by snailrowen1337** [e-bug/iglue#13]
I want to try the iGLUE evaluation. I started with the file

```
iglue/experiments/zero_shot/ctrl_vilbert/marvl/test.en.dtu.sh
```

However, after installation, this fails with the error

```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co//home/projects/ku_00062/huggingface/bert-base-uncased/resolve/main/config.json
```

Is this error expected? 

If I change `  --bert_model /home/projects/ku_00062/huggingface/bert-base-uncased
` into `  --bert_model bert-base-uncased ` the model runs. But then the script complains about finding the extracted features from `nlvr2_boxes36.h5`. Is there any way to disable using extracted features? Thanks!!

**Comment by e-bug** [comment]
Hi,

> If I change --bert_model /home/projects/ku_00062/huggingface/bert-base-uncased into --bert_model bert-base-uncased the model runs.

Yes, that's correct. I was passing a local path since nodes in our cluster don't have internet access.

> But then the script complains about finding the extracted features from nlvr2_boxes36.h5

You need to run [this script](https://github.com/e-bug/iglue/blob/main/features_extraction/h5_to_lmdb.py) to convert from H5 to LMDB (cf. the [datasets readme](https://github.com/e-bug/iglue/blob/main/datasets/README.md))

**Comment by snailrowen1337** [comment]
Thanks for the reply!

> Yes, that's correct. I was passing a local path since nodes in our cluster don't have internet access.

Got it, that makes sense!

> You need to run [this script](https://github.com/e-bug/iglue/blob/main/features_extraction/h5_to_lmdb.py) to convert from H5 to LMDB (cf. the [datasets readme](https://github.com/e-bug/iglue/blob/main/datasets/README.md))

I wanted specifically to disable using extracted features altogether. I.e. not use H5 or LMDB files with extracted features, but instead use the forward pass of a model. Is that possible? Thanks!

**Comment by e-bug** [comment]
The current models were pretrained to use RoIs, so you need pass the extracted features for the forward pass.
