### ISSUE TITLE
expired urls for WIT retrieval dataset

### ISSUE THREAD

**Issue by ghchen18** [e-bug/iglue#2]
Hi, 

I use the img2dataset tool to download the WIT images, some urls are expired and the corresponding images are not available. Can you provide the original image files of the WIT part for downloading? Thanks a lot.

**Comment by e-bug** [comment]
Hi,

Thanks for pointing this out and reminding me of the missing images.

I will have some time to look into this next week.
If you don't want to wait for me, you can download all the data from the [Kaggle competition](https://www.kaggle.com/c/wikipedia-image-caption/data) and select the images based on the `image_url` field.

**Comment by ghchen18** [comment]
OK. Got it.
Many thanks.
