### ISSUE TITLE
Question on "config.fusion_method"!

### ISSUE THREAD

**Issue by nooralahzadeh** [e-bug/iglue#3]
Hi,
It seems that on the `vgqa` experiments you use the `config.fusion_method="text" `! I wonder why you don't consider the pooling of both image and text! or if you have any results on the other `config.fusion_methods`?

Thanks

**Comment by e-bug** [comment]
Hi,

Can you point me to the file you are referring to?

The fusion_method is architecture-dependent: some use text+vision (i.e. `[CLS]` + `[IMG]`) pooling, others just text (`[CLS]`) pooling.

**Comment by nooralahzadeh** [comment]
UC2, MP3 !

**Comment by e-bug** [comment]
Yes, those models only use the [CLS] representations as input to the pooling layer.

**Comment by nooralahzadeh** [comment]
Thanks.

**Comment by nooralahzadeh** [comment]
Thanks
