### ISSUE TITLE
'.' caption in arabic test set in WIT

### ISSUE THREAD

**Issue by memory4963** [e-bug/iglue#7]
Hi, thank you very much for these excellent datasets.

I found there is a sample in arabic test set in WIT (test_ar.jsonl) whose caption is only a '.'
Should I keep or remove it from the test set?

FYI
```
wit_ix: wit-test_7382
page_url: https://ar.wikipedia.org/wiki/%D8%B3%D9%8A%D9%86%D8%B1%D9%88%D9%83_%D9%85%D8%A7%D8%B1%D9%8A
meta_url: http://commons.wikimedia.org/wiki/File:SinrokMary1918Sunset.tif
image_url: https://upload.wikimedia.org/wikipedia/commons/8/81/SinrokMary1918Sunset.tif
```

**Comment by e-bug** [comment]
Hi, thanks for reporting this! I did not expect such an issue within the WIT test data.
Please remove the sample, I will do the same.

**Comment by memory4963** [comment]
OK, thank you very much!
