### ISSUE TITLE
Number of classes in gqa and xgqa?

### ISSUE THREAD

**Issue by nooralahzadeh** [e-bug/iglue#8]
Hi,
I wonder about the number of classes in `gqa` and `xgqa` datasets?  It is reported `1,842` labels, however, it is `1,853` in the original papers!
Thanks

**Comment by e-bug** [comment]
Hi, I used `1,842` as it corresponds to all the labels in train + validation.

**Comment by nooralahzadeh** [comment]
Does it mean there are some labels `1,853-1,842=11` in the test set which has not been seen during the training?

**Comment by e-bug** [comment]
I do not remember how they computed the labels for GQA.
In my case, I simply took all the train + validation labels.
Let me know if you find out!
